# This workflow will check flake style
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docs Deploy

on:
  push:
    branches: [ main, 'doc/*', 'dev/*' ]
  release:
    types: [ published ]

jobs:
  doc:
    name: Documentation Generation
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        os:
          - 'ubuntu-18.04'
        python-version:
          - '3.7'

    services:
      plantuml:
        image: plantuml/plantuml-server
        ports:
          - 18080:8080

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - name: Show Python Version
        run: |
          python -V
      - name: Set up system dependences on linux
        run: |
          sudo apt-get update
          sudo apt-get install -y tree cloc wget curl make graphviz rsync
          sudo apt-get install -y libxml2-dev libxslt-dev python-dev  # need by pypy3
          dot -V
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade flake8 setuptools wheel twine
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install -r requirements-doc.txt
      - name: Test the basic environment
        run: |
          python -V
          pip --version
          pip list
          tree .
          cloc pyspj
          cloc test
      - name: Generate
        env:
          ENV_PROD: 'true'
          PLANTUML_HOST: http://127.0.0.1:18080
        run: |
          git fetch --all --tags
          git branch -av
          git remote -v
          git tag
          plantumlcli -c
          make pdocs
          mv ./docs/build/html ./public
      - name: Deploy to Github Page
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
